# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'firebasesample' do
pod 'Firebase', '>= 2.5.1'
end

