# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'samlesocket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
#  pod 'Socket.IO-Client-Swift', '~> 6.1.5'

#    pod 'Starscream', '~> 1.1.3'

  # Pods for samlesocket

end
